module:
  imports:
  - path: github.com/krzysztofgb/lazyimg
  - path: github.com/krzysztofgb/examples
  # replacements forces using local version for dev instead of using the remote:
  replacements:
  - github.com/krzysztofgb/lazyimg -> ../../.

# disableKinds is only needed for this exampleSite to surpress some warnings:
disableKinds: ["taxonomy", "term"]

Params:
  lazyimg:
    resizer: auto
    renderer: lqip

    # Resizer options:
    lqipSize: "120x Gaussian"
    maxSize: "1920x"
    responsiveSizes: ["320x", "640x", "768x", "1024x", "1366x", "1600x", "1920x"]
    resizeOptions: "Lanczos q95"

    # Renderer options:
    class: "my-img-class"
    alt: "My logo"
    noscript: true

    errorHandler: warning-remote